# Generated by Django 2.1 on 2020-04-29 01:09

from django.db import migrations
import os

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200427_0006'),
    ]
    def generate_superuser(apps, schema_editor):

        from django.contrib.auth import get_user_model

        DJANGO_SU_NAME = os.environ.get('USERNAME')

        superuser = get_user_model().objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_NAME +"@localhost.localhost",
            password=DJANGO_SU_NAME
        )

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
