# Generated by Django 2.1 on 2020-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDonations',
            new_name='User_Donations',
        ),
    ]
