# Generated by Django 2.1 on 2020-04-21 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200420_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_donations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
