# Generated by Django 2.1 on 2020-04-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200423_2049'),
        ('projects', '0006_project_is_featured'),
    ]

    operations = [
    ]
