# Generated by Django 2.1 on 2020-04-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_comment_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_reports',
            options={'verbose_name': 'Comment Report', 'verbose_name_plural': 'Comment Reports'},
        ),
        migrations.AlterModelOptions(
            name='project_reports',
            options={'verbose_name': 'Project Report', 'verbose_name_plural': 'Project Reports'},
        ),
    ]
